language: python
python: 3.6
os: linux
dist: trusty

addons:
  postgresql: "9.6"

services:
  - postgresql



before_install:
  - sudo apt update
  - sudo apt install -y build-essential libssl-dev libffi-dev libpq-dev libmagickwand-dev

install:
  - sudo mkdir -p /var/regovar/{cache,downloads,files,pipelines,jobs,databases/hg19,databases/hg38}
  - sudo chown -R `whoami`:`whoami` /var/regovar
  - cd /var/regovar/databases/hg38
  - wget http://hgdownload.soe.ucsc.edu/goldenPath/hg38/database/refGene.txt.gz
  - gunzip refGene.txt.gz
  - cd /var/regovar/databases/hg19
  - wget http://hgdownload.soe.ucsc.edu/goldenPath/hg19/database/refGene.txt.gz
  - gunzip refGene.txt.gz



before_script:
  - cd /home/travis/build/REGOVAR/Regovar
  - psql -c "CREATE USER regovar WITH PASSWORD 'regovar';" -U postgres
  - psql -c "CREATE DATABASE regovar OWNER regovar;" -U postgres

script:
  - pip install -r requirements.txt
  - cd regovar
  - make init
  - make install
  - make update_hpo
  - psql -U regovar -d regovar -f tests/init_fake_data.sql
  - pip install blessings
  - echo "TODO ! python tests.py"


branches:
  only:
    - master
