dist: trusty
sudo: false

language: node_js
node_js:
  - '11'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

install:
  - cd absg-core
  - npm install

script:
  - npm build
#  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessNoSandbox


branches:
  only:
    - master
