language: python
python: 3.6
os: linux
dist: trusty

addons:
  postgresql: "9.6"

services:
  - postgresql



before_install:
  - sudo apt update
  - sudo apt install -y build-essential libssl-dev libffi-dev libpq-dev libmagickwand-dev

install:
  - sudo mkdir -p /var/absg/v5/dev{cache,downloads,files}
  - sudo chown -R `whoami`:`whoami` /var/absg



before_script:
  - cd /home/travis/build/ikit/AbsG5
  - psql -c "CREATE USER absg WITH PASSWORD 'absg';" -U postgres
  - psql -c "CREATE DATABASE absg OWNER absg;" -U postgres

script:
  - pip install -r requirements.txt
  - cd absg
  - make init
  - make install
  - psql -U absg -d absg -f tests/init_fake_data.sql
  - pip install blessings
  - echo "TODO ! python tests.py"


branches:
  only:
    - master
