site_name: Absolument G (v5)
theme: readthedocs
markdown_extensions:
 - extra
 - nl2br
 - sane_lists
 - abbr
 - attr_list
 - def_list
 - tables 
pages:
 - 'ACCUEIL': 'index.md'
 - 'INSTALLATION':
    - 'Serveur': 'installation/server.md'
    - 'Client': 'installation/client.md'
    - 'Configuration': 'installation/configuration.md'
 - 'UTILISATEUR': 
    - 'Présentation': 'user/presentation.md'
    - 'Conceptes de base': 'user/concepts.md'
    - 'Citation': 'user/citation.md'
    - 'Immt': 'user/immt.md'
    - 'Forum': 'user/forum.md'
    - 'Agenda': 'user/agenda.md'
    - 'Web3G': 'user/web.md'
    - 'AGPA': 'user/agpa.md'
    - 'Grenier': 'user/grenier.md'
    - 'FAQ': 'user/faq.md'
 - 'MAINTENANCE':
    - 'Serveur': 'maintenance/server.md'
    - 'Client': 'maintenance/client.md'
 - 'DÉVELOPPEUR':
    - 'Outils': 'developper/community.md'
    - 'Bonnes pratiques': 'developper/good_practices.md'
    - 'Architecture': 'developper/architecture.md'
    - 'Database': 'developper/database.md'
    - 'Core': 'developper/core.md'
    - 'Modules personalisables': 'developper/modules.md'
    - 'API rest': 'developper/rest.md'
    - 'API cli': 'developper/cli.md'
    - 'Authentification': 'developper/authentication.md'
    - 'Gestion des erreurs': 'developper/errors.md'
    
 
