version: '3.5'

networks:
  absg5_net:
    name: absg5_net

services:
  absg5_nextcloud_db:
    container_name: absg5_nextcloud_db
    image: postgres
    restart: always
    volumes:
      - /var/absg5/nextcloud_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    networks:
      - absg5_net

  absg5_nextcloud:
    container_name: absg5_nextcloud
    image: nextcloud:apache
    volumes:
      - /var/absg5/nextcloud:/var/www/html
    depends_on:
      - absg5_nextcloud_db
    environment:
      - POSTGRES_USER=nextcloud
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD=nextcloud
      - POSTGRES_HOST=absg5_nextcloud_db
    networks:
      - absg5_net
    ports:
      - "10011:80"
