version: '3.5'

networks:
  absg5_net:
    name: absg5_net

services:
  absg5_db:
    container_name: absg5_db
    image: postgres
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: always
    volumes:
      - /var/absg5/db:/var/lib/postgresql/data
      - /var/absg5/config/postgres.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=absg
      - POSTGRES_PASSWORD=absg
      - POSTGRES_DB=absg
    networks:
      - absg5_net
    user: "${UID}:${GID}"

  absg5_core:
    container_name: absg5_core
    build: .
    image: absg5
    links:
      - absg5_db
    depends_on:
      - absg5_db
    restart: always
    networks:
      - absg5_net
    user: "${UID}:${GID}"
    ports:
      - "10011:9000"
